name: SQL for GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - synchronize

jobs:
  build:
    
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

  deploy_ddl_procedures:
    if: $(find DDL/Procedures -type f -name '*.sql' | wc -l) -gt 0 
    needs: build
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy DDL Procedures
      uses: azure/sql-action@v2.2.1
      with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './DDL/StoredProcedures/*.sql'
          action: 'publish'
    - name: Logout
      run: az logout

  deploy_dml_procedures:
    if: $(find DML/Procedures -type f -name '*.sql' | wc -l) -gt 0
    needs: build
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy DML Procedures
      uses: azure/sql-action@v2.2.1
      with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './DML/StoredProcedures/*.sql'
          action: 'publish'
    - name: Logout
      run: az logout

  deploy_ddl_functions:
    if: ${{ github.event.pull_request.merged == 'true' || github.event_name == 'push' }}
    needs: build
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy DDL Functions
      uses: azure/sql-action@v2.2.1
      with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './DDL/Functions/*.sql'
          action: 'publish'
    - name: Logout
      run: az logout

  deploy_dml_functions:
    if: ${{ github.event.pull_request.merged == 'true' || github.event_name == 'push' }}
    needs: build
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy DML Functions
      uses: azure/sql-action@v2.2.1
      with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './DML/Functions/*.sql'
          action: 'publish'
    - name: Logout
      run: az logout
