name: SQL for GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  build:
    if: ${{ github.event.pull_request.merged }} == "true" || ${{ github.event_name }}" == "push"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Execute SQL Scripts
      run: |
        # Check if the event is a pull_request and if it's merged
        # if ([ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.event.pull_request.merged }}" == "true" ]||
        #    [ "${{ github.event_name }}" == "push" ]); then

          echo "Executing SQL scripts."

          # Define the path to your SQL files
          # sql_files_path='./sql-scripts'
          
          # Get a list of SQL files
          # sql_files=($(find $sql_files_path -name '*.sql'))

          # Loop through SQL files and execute them
          # for file in "${sql_files[@]}"; do
          #   echo "Executing SQL script: $file"
            az sql db exec-mssql-command --connection-string ${{ secrets.AZURE_SQL_CONNECTION_STRING }} --query "$(cat ./testing.sql)"
          done
        else
          echo "Workflow not triggered for this event."
        fi

    - name: Logout
      run: az logout
