name: SQL for GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

  # deploy_ddl_procedures:
  #   needs: build
  #   runs-on: windows-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v1
  #   - name: Check if files exist
  #     run: |
  #       .\check_files_exist.ps1 -sqlFolderPath "DDL\StoredProcedures\"
  #   - name: Debug
  #     run: echo "Deploy=${{ env.deploy}}" 
  #   - name: Join SQL Files
  #     run: |
  #       .\join_sql_files.ps1 -sqlFolderPath "DDL\StoredProcedures\" -outputFolderPath "DDL\StoredProcedures\" -outputFileName "DDLProcedures.sql"
  #     if: ${{ env.deploy =='true' }} 
  #   - name: Azure Login
  #     uses: azure/login@v1
  #     with:
  #       creds: ${{ secrets.AZURE_CREDENTIALS }}
  #     if: ${{ env.deploy =='true' }} 
  #   - name: Deploy DDL Procedures
  #     uses: azure/sql-action@v2.2.1
  #     with:
  #         connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
  #         path: './DDL/StoredProcedures/DDLProcedures.sql'
  #         action: 'publish'
  #     if: ${{ env.deploy =='true' }} 
  #   - name: Upload DDL Procedure as Artifact 
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: ddl-procedures-artifact
  #       path: './DDL/StoredProcedures/DDLProcedures.sql'
  #     if: ${{ env.deploy =='true' }} 
  #   - name: Logout
  #     run: az logout
  #     if: ${{ env.deploy =='true' }} 
      
  deploy_tables:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Create All Tables
      uses: azure/sql-action@v2.2.1
      with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './create_all_tables.sql'
          action: 'publish'
    - name: Upload Create table script as Artifact 
      uses: actions/upload-artifact@v2
      with:
        name: create-tables-artifact
        path: './create_all_tables.sql'
    - name: Logout
      run: az logout

  deploy_procedures:
    needs: deploy_tables
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Load All Procedures
      uses: azure/sql-action@v2.2.1
      with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './create_all_procedures.sql'
          action: 'publish'
    - name: Upload Create Procedures script as Artifact 
      uses: actions/upload-artifact@v2
      with:
        name: create-tables-artifact
        path: './create_all_procedures.sql'
    - name: Logout
      run: az logout  

  deploy_views:
    needs: deploy_procedures
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Load All Views
      uses: azure/sql-action@v2.2.1
      with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './create_all_views.sql'
          action: 'publish'
    - name: Upload Create Views script as Artifact 
      uses: actions/upload-artifact@v2
      with:
        name: create-tables-artifact
        path: './create_all_views.sql'
    - name: Logout
      run: az logout    

  deploy_functions:
    needs: deploy_views
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Load All Views
      uses: azure/sql-action@v2.2.1
      with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './create_all_functions.sql'
          action: 'publish'
    - name: Upload Create Views script as Artifact 
      uses: actions/upload-artifact@v2
      with:
        name: create-tables-artifact
        path: './create_all_functions.sql'
    - name: Logout
      run: az logout 

  deploy_triggers:
    needs: deploy_functions
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Load All Triggers
      uses: azure/sql-action@v2.2.1
      with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './create_all_triggers.sql'
          action: 'publish'
    - name: Upload Create Views script as Artifact 
      uses: actions/upload-artifact@v2
      with:
        name: create-triggers-artifact
        path: './create_all_triggers.sql'
    - name: Logout
      run: az logout 

  deploy_constants:
    needs: deploy_functions
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Populate all constants
      uses: azure/sql-action@v2.2.1
      with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './populate_constants.sql'
          action: 'publish'
    - name: Upload Create Views script as Artifact 
      uses: actions/upload-artifact@v2
      with:
        name: create-constants-artifact
        path: './populate_constants.sql'
    - name: Logout
      run: az logout 
