name: SQL for GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - synchronize

jobs:
  build:
    
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

  deploy_ddl_procedures:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Check if files exist
      run: |
        $sqlFiles = Get-ChildItem -Path DDL\StoredProcedures\ -Filter *.sql
        if ($sqlFiles.Count -gt 0) {
          Write-Output "SQL files exist in the DDL/StoredProcedures folder. Proceeding with deployment."
          echo "deploy=true" >> $GITHUB_ENV
          Write-Output "${{ env.deploy }}"
        } else {
          Write-Output "No SQL files found in the DDL/StoredProcedures folder. Skipping deployment."
          echo "deploy=false" >> $GITHUB_ENV
        }
    - name: Join SQL Files
      run: |
        .\join_sql_files.ps1 -sqlFolderPath "DDL\StoredProcedures\" -outputFolderPath "DDL\StoredProcedures\" -outputFileName "DDLProcedures.sql"
      if: ${{ env.deploy }} == "true"   
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      if: ${{ env.deploy }} == "true"
    - name: Deploy DDL Procedures
      uses: azure/sql-action@v2.2.1
      with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './DDL/StoredProcedures/DDLProcedures.sql'
          action: 'publish'
      if: ${{ env.deploy }} == "true"
    - name: Logout
      run: az logout
      if: ${{ env.deploy }} == "true"


  deploy_dml_procedures:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      
    - name: Check if files exist
      run: |
        $sqlFiles = Get-ChildItem -Path DML\StoreProcedures\ -Filter *.sql
        if ($sqlFiles.Count -gt 0) {
          Write-Output "SQL files exist in the DML/StoreProcedures folder. Proceeding with deployment."
          echo "deploy=true" >> $GITHUB_STATE/deploy
        } else {
          Write-Output "No SQL files found in the DML/StoreProcedures folder. Skipping deployment."
          echo "deploy=false" >> $GITHUB_STATE/deploy
        }
    - name: Join SQL Files
      run: |
        .\join_sql_files.ps1 -sqlFolderPath "DML\StoreProcedures\" -outputFolderPath "DML\StoreProcedures\" -outputFileName "DMLProcedures.sql"
      if: ${{ env.deploy }} == "true"           
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      if: env.GITHUB_STATE_deploy == 'true'
    - name: Deploy DML Procedures
      uses: azure/sql-action@v2.2.1
      with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './DML/StoreProcedures/DMLProcedures.sql'
          action: 'publish'
      if: env.GITHUB_STATE_deploy == 'true'
    - name: Logout
      run: az logout
      if: env.GITHUB_STATE_deploy == 'true'


  deploy_ddl_functions:
    if: ${{ github.event.pull_request.merged == 'true' || github.event_name == 'push' }}
    needs: build
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Check if files exist
      run: |
        $sqlFiles = Get-ChildItem -Path DDL\Functions\ -Filter *.sql
        if ($sqlFiles.Count -gt 0) {
          Write-Output "SQL files exist in the DDL\Functions folder. Proceeding with deployment."
          echo "deploy=true" >> $GITHUB_STATE/deploy
        } else {
          Write-Output "No SQL files found in the DDL\Functions folder. Skipping deployment."
          echo "deploy=false" >> $GITHUB_STATE/deploy
        }
    - name: Join SQL Files
      run: |
        .\join_sql_files.ps1 -sqlFolderPath "DDL\Functions\" -outputFolderPath "DDL\Functions\" -outputFileName "DDLFunctions.sql"
      if: ${{ env.deploy }} == "true"  
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      if: env.GITHUB_STATE_deploy == 'true'
    - name: Deploy DDL Functions
      uses: azure/sql-action@v2.2.1
      with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './DDL/Functions/DDLFunctions.sql'
          action: 'publish'
      if: env.GITHUB_STATE_deploy == 'true'
    - name: Logout
      run: az logout
      if: env.GITHUB_STATE_deploy == 'true'

  deploy_dml_functions:
    if: ${{ github.event.pull_request.merged == 'true' || github.event_name == 'push' }}
    needs: build
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Check if files exist
      run: |
        $sqlFiles = Get-ChildItem -Path DML\Functions\ -Filter *.sql
        if ($sqlFiles.Count -gt 0) {
          Write-Output "SQL files exist in the DML\Functions folder. Proceeding with deployment."
          echo "deploy=true" >> $GITHUB_STATE/deploy
        } else {
          Write-Output "No SQL files found in the DML\Functions folder. Skipping deployment."
          echo "deploy=false" >> $GITHUB_STATE/deploy
        }
    - name: Join SQL Files
      run: |
        .\join_sql_files.ps1 -sqlFolderPath "DML\Functions\" -outputFolderPath "DML\Functions\" -outputFileName "DMLFunctions.sql"
      if: ${{ env.deploy }} == "true"  
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      if: env.GITHUB_STATE_deploy == 'true'
    - name: Deploy DML Functions
      uses: azure/sql-action@v2.2.1
      with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './DML/Functions/DMLFunctions.sql'
          action: 'publish'
      if: env.GITHUB_STATE_deploy == 'true'          
    - name: Logout
      run: az logout
      if: env.GITHUB_STATE_deploy == 'true'
